# Week 2 Summary
> NAME: $\color{red}{\text{    Yuan Ji     }}$
> 
> PID: $\color{red}{\text{    A16822092     }}$
>
> 
---

I certify that the following write-up is my own work, and have abided by the UCSD Academic Integrity Guidelines.

- [x] Yes
- [ ] No

% # %load tex-macros
<div hidden>
\newcommand{\require}[1]{}

$\require{begingroup}\require{newcommand}$
$\long\def \forcecommand #1{\providecommand{#1}{}\renewcommand{#1}}$
$\forcecommand{\defeq}{\stackrel{\small\bullet}{=}}$
$\forcecommand{\ra}{\rangle}$
$\forcecommand{\la}{\langle}$
$\forcecommand{\pr}{{\mathbb P}}$
$\forcecommand{\qr}{{\mathbb Q}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\av}{{\boldsymbol{a}}}$
$\forcecommand{\bv}{{\boldsymbol{b}}}$
$\forcecommand{\cv}{{\boldsymbol{c}}}$
$\forcecommand{\dv}{{\boldsymbol{d}}}$
$\forcecommand{\ev}{{\boldsymbol{e}}}$
$\forcecommand{\fv}{{\boldsymbol{f}}}$
$\forcecommand{\gv}{{\boldsymbol{g}}}$
$\forcecommand{\hv}{{\boldsymbol{h}}}$
$\forcecommand{\nv}{{\boldsymbol{n}}}$
$\forcecommand{\sv}{{\boldsymbol{s}}}$
$\forcecommand{\tv}{{\boldsymbol{t}}}$
$\forcecommand{\uv}{{\boldsymbol{u}}}$
$\forcecommand{\vv}{{\boldsymbol{v}}}$
$\forcecommand{\wv}{{\boldsymbol{w}}}$
$\forcecommand{\zerov}{{\mathbf{0}}}$
$\forcecommand{\onev}{{\mathbf{0}}}$
$\forcecommand{\phiv}{{\boldsymbol{\phi}}}$
$\forcecommand{\cc}{{\check{C}}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\Xv}{{\boldsymbol{X}\!}}$
$\forcecommand{\yv}{{\boldsymbol{y}}}$
$\forcecommand{\Yv}{{\boldsymbol{Y}}}$
$\forcecommand{\zv}{{\boldsymbol{z}}}$
$\forcecommand{\Zv}{{\boldsymbol{Z}}}$
$\forcecommand{\Iv}{{\boldsymbol{I}}}$
$\forcecommand{\Jv}{{\boldsymbol{J}}}$
$\forcecommand{\Cv}{{\boldsymbol{C}}}$
$\forcecommand{\Ev}{{\boldsymbol{E}}}$
$\forcecommand{\Fv}{{\boldsymbol{F}}}$
$\forcecommand{\Gv}{{\boldsymbol{G}}}$
$\forcecommand{\Hv}{{\boldsymbol{H}}}$
$\forcecommand{\alphav}{{\boldsymbol{\alpha}}}$
$\forcecommand{\epsilonv}{{\boldsymbol{\epsilon}}}$
$\forcecommand{\betav}{{\boldsymbol{\beta}}}$
$\forcecommand{\deltav}{{\boldsymbol{\delta}}}$
$\forcecommand{\gammav}{{\boldsymbol{\gamma}}}$
$\forcecommand{\etav}{{\boldsymbol{\eta}}}$
$\forcecommand{\piv}{{\boldsymbol{\pi}}}$
$\forcecommand{\thetav}{{\boldsymbol{\theta}}}$
$\forcecommand{\tauv}{{\boldsymbol{\tau}}}$
$\forcecommand{\muv}{{\boldsymbol{\mu}}}$
$%$
$\forcecommand{\sd}{\text{SD}}$
$\forcecommand{\se}{\text{SE}}$
$\forcecommand{\med}{\text{median}}$
$\forcecommand{\median}{\text{median}}$
$%$
$\forcecommand{\supp}{\text{supp}}$
$\forcecommand{\E}{\mathbb{E}}$
$\forcecommand{\var}{\text{Var}}$
$\forcecommand{\Ber}{{\text{Ber}}}$
$\forcecommand{\Bin}{{\text{Bin}}}$
$\forcecommand{\Geo}{{\text{Geo}}}$
$\forcecommand{\Unif}{{\text{Unif}}}$
$\forcecommand{\Poi}{{\text{Poi}}}$
$\forcecommand{\Exp}{{\text{Exp}}}$
$\forcecommand{\Chisq}{{\chi^2}}$
$\forcecommand{\N}{\mathbb{N}}$
$\forcecommand{\iid}{{\stackrel{iid}{\sim}}}$
$\forcecommand{\px}{p_{X}}$
$\forcecommand{\fx}{f_{X}}$
$\forcecommand{\Fx}{F_{X}}$
$\forcecommand{\py}{p_{Y}}$
$\forcecommand{\pxy}{p_{X,Y}}$
$\forcecommand{\po}{{p_0}}$
$\forcecommand{\pa}{{p_a}}$
$\forcecommand{\Xbar}{\overline{X}}$
$\forcecommand{\Ybar}{\overline{Y}}$
$\forcecommand{\Zbar}{\overline{Z}}$
$\forcecommand{\nXbar}{n \cdot \overline{X}}$
$\forcecommand{\nYbar}{n \cdot \overline{Y}}$
$\forcecommand{\nZbar}{n \cdot \overline{Z}}$
$\forcecommand{\Xn}{X_1, X_2, \dots, X_n}$
$\forcecommand{\Xm}{{X_1, X_2, \dots, X_m}}$
$\forcecommand{\Yn}{Y_1, Y_2, \dots, Y_n}$
$\forcecommand{\Ym}{{Y_1, Y_2, \dots, Y_m}}$
$\forcecommand{\sumXn}{X_1 + X_2 + \dots + X_n}$
$\forcecommand{\sumym}{Y_1 + Y_2 + \dots + Y_m}$
$\forcecommand{\la}{\ell_\alpha}$
$\forcecommand{\ua}{u_\alpha}$
$\forcecommand{\at}{{\alpha/2}}$
$\forcecommand{\mux}{\mu_{X}}$
$\forcecommand{\muy}{\mu_{Y}}$
$\forcecommand{\sx}{\sigma_{X}}$
$\forcecommand{\sy}{\sigma_{Y}}$
$\forcecommand{\ci}{\text{CI}}$
$\forcecommand{\pvalue}{$p$-value}$
$\forcecommand{\Ho}{H_{0}}$
$\forcecommand{\Ha}{H_{a}}$

\vskip-\parskip
\vskip-\baselineskip
</div>

In [10]:
import numpy as np
import scipy
from scipy import stats as stats

---

## Key Takeaways from Week 1


#### Tuesday: 

We reviewed the concepts of probability and some statistical fundamentals, including random variables, cdf, pmf, pdf, and $\E(X)$ and $\var(X)$, as well as some common statistical distributions.

#### Thursday

We continued the discussion of statistical distributions, and then reviewed the Confidence Intervals & Hypothesis Testing, including the one sample proportion and two sample proportions, the CI for difference of two proportions. Also, we went over the concepts of quantiles and empirical CDFs in the beginning of the lecture.

---

## Tue, Apr 9th

#### Probability Review

Given a sample space $\mathcal{S}$ and an event $A$, there are three qualiatively different ways to define the probability $\pr(A)$:

**Empiricial Probability**: based on repeatedly observing the outcome of an event


$$
\pr(A) = \frac{\text{\# of times A occurs}}{\text{\# of trials}}
$$

An example of empirical probability is the following scenario:

> A student takes 10 multiple-choice quizzes, correctly answering the first question 6 times. The empirical probability that the student correctly answers the first question on the next quiz is $\frac{6}{10}$ = 0.6 or 60%, based on their past performance.

**Theoretical Probability**: based on the assumption of a model


$$
\pr(A) = \frac{\text{\# of ways A can occur}}{\text{\# of possible outcomes}}
$$

An example of theoretical probability is the following scenario:

> For a fair six-sided die, each face of the die is equally likely to land facing up when rolled. The theoretical probability of rolling a 1 is $\frac{6}{10}$.

**Subjective Probability**: based on person's opinion


$$
\pr(A) = \text{degree of belief that A will occur}
$$

#### Random Variables

Intuitively, a random variable $X$ is a way to quantify the uncertainty of an outcome in a situation where different results are possible and, 

the support of a random variable, denoted $\text{supp}(X)$, is the set of all possible values it can take.


A random variable $X$ can have different types of supports. 

1. **categorical**: The support has different categories, but there's no way of comparing "≤" or "≥" between two categories
    - e.g., $\supp(X) = \{ \text{red}, \text{green}, \text{blue} \}$
    - e.g., $\supp(X) = \{ \text{car}, \text{bus}, \text{boat} \}$

2. **Ordinal**: The support has different categories, but we can compare "≤" or "≥" between two categories but **cannot quantify the difference** between them
    - e.g., $\supp(X) = \{ \text{low}, \text{med}, \text{hi} \}$
    - e.g., $\supp(X) = \{ \text{cold}, \text{warm}, \text{hot} \}$
    - e.g., $\supp(X) = \{ \text{uncomfortable}, \text{meh}, \text{comfortable} \}$
3. **Discrete**: The support is a discrete collection of objects where we can compare "≤" or "≥" between two categories **and** quantify the difference between them
    - e.g., $\supp(X) = \{ 0, 1 \}$
    - e.g., $\supp(X) = \{ 0, \frac{1}{10}, \frac{2}{10}, \cdots, \frac{9}{10}, 1 \}$
    - e.g., $\supp(X) = \{ a, a+1, \cdots, b-1, b \}$ for $a < b$
    - e.g., $\supp(X) = \{ 0, 1, 2, \cdots \}$
    
    Notably, a random variable is discrete if there is a finite precision to the measurement of the outcome
4. **Continuous**: The support is a continuum, 
    - e.g., $\supp(X) = [a, b]$ for $a < b$ is an interval
    - e.g., $\supp(X) = \R$ is the whole real line
    - e.g., $\supp(X) = \R^d$ for any $d = 1, 2, 3, \dots$

#### Properties of Random Variables

**Cumulative Distribution Function**

Intuitively, the cumulative distribution function (CDF) of a random variable $X$ measures the probability that $X$ will take a value less than or equal to a specific number.

For a random variable $X$ with PDF $\fx(x)$ the CDF $\Fx(x)$ is given by
$$
\Fx(x)  = \int_{-\infty}^x f_X(y) dy 
$$
(formula for CDF of continuous RV)


**Expected value**

For a random variable $X$ with PMF $\px$ or with PDF $\fx$, the expected value of $X$ is

$$
\E(X) = \sum_{x \in \text{supp}(X)} x \cdot p_X(x) \quad \text{if } X \text{ is discrete}
$$

(formula for PMF)
$$
\E(X) = \int_{-\infty}^\infty x \cdot f_X(x) \, dx \quad \text{if } X \text{ is continuous}
$$
(formula for PDF)

**Variance**

For a random variable $X$ with expected value $\E(X)$ and second moment $\E(X^2)$, the variance of $X$ is


$$
\begin{aligned}
\var(X) &= \mathbb{E}\Big( \{\; X - \mathbb{E}(X) \;\}^2  \Big) = \E(X^2) - \E(X)^2 \\
\end{aligned}
$$

(formula for variance)

#### Examples of Probability Distributions

---

§1. Bernoulli distribution

A random variable $X \sim \Ber(p)$ follows a Bernoulli distribution with parameter $p$.

* The support is
$$
\supp(X) = \{0, 1\}
$$
* The PMF is 
$$
\px(x) = \begin{cases}
p & \text{if } x = 1 \\
1-p & \text{if } x = 0 \\
\end{cases}
$$
* The expected value is
$$
\begin{aligned}
\mathbb{E}(X) 
&= \sum_{x \in \text{supp}(X)} x \cdot p_X(x) \\
&= 0 \cdot (1-p) + 1 \cdot p \\
&= p
\end{aligned}
$$
* The variance is
$$
\begin{aligned}
\text{Var}(X) 
&= \mathbb{E}(X^2) - \mathbb{E}(X)^2 \\
&= p - p^2 \\
&= p(1-p)
\end{aligned}
$$

In python, we can generate $10$ random samples from a Bernoulli distribution as follows:

In [11]:
# Define the probability of success
p = 0.5

# Generate 10 random samples from a Bernoulli distribution
X = stats.bernoulli(p)
X.rvs(10)

array([0, 1, 1, 0, 0, 1, 1, 1, 1, 1], dtype=int64)

---

§2. Discrete Uniform distribution

A random variable $X \sim \Unif \{a, b\}$ follows a _discrete uniform_ distribution with parameter(s) $a,b$.

* The support is
$$
\supp(X) = \{a, a+1, a+2, \dots, b\}

$$
* The PMF is 
$$
\px(x) = \begin{cases}
\displaystyle\frac{1}{b-a+1} & \text{if } x \in \text{supp}(X) \\ \\
0 & \text{otherwise}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \frac{a+b}{2}
$$
* The variance is
$$
\var(X) = \frac{(b-a+1)^2 - 1}{12}
$$

We can generate $10$ random samples from a discrete uniform distribution as follows:

In [12]:
# Define the lower and upper bounds of the distribution, inclusive
a = 1
b = 10

# Generate 10 random samples from a discrete uniform distribution
X = np.random.randint(a, b + 1, size=10)

X

array([9, 2, 1, 1, 4, 3, 5, 6, 9, 9])

---

§3. Poisson Distribution

A random variable $X \sim \Poi(\lambda)$ follows a _Poisson_ distribution with parameter(s) $\lambda$.

* The support is
$$
\supp(X) = \{0, 1, 2, \ldots\}
$$
* The PMF is 
$$
\px(x) = \begin{cases}
\displaystyle\frac{\lambda^x}{x!} e^{-\lambda} & \text{if } x = 0, 1, 2, \dots \\
0 & \text{otherwise}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \lambda
$$
* The variance is
$$
\var(X) = \lambda 
$$

We can generate $10$ random samples from a Poisson distribution as follows:

In [13]:
# Define the rate parameter lambda
lambda_param = 1

# Generate 10 random samples from a Poisson distribution
X = stats.poisson(lambda_param)
X.rvs(10)

array([1, 2, 0, 1, 1, 0, 2, 0, 1, 0], dtype=int64)

---

§4. Exponential distribution

A random variable $X \sim \Exp(\lambda)$ follows an _Exponential_ distribution with parameter(s) $\lambda$.

* The support is
$$
\supp(X) = [0, \infty)
$$
* The PDF is 
$$
\fx(x) = \begin{cases}
\lambda e^{-\lambda x} & \text{if } x \geq 0 \\
0 & \text{otherwise}
\end{cases}
$$
* The expected value is
$$
\mathbb E(X) = \frac{1}{\lambda}
$$
* The variance is
$$
\var(X) = \frac{1}{\lambda^2}
$$

We can generate $10$ random samples from an Exponential distribution as follows:

In [14]:
# Define the rate parameter lambda
lambda_param = 2 

# Generate 10 random samples from an Exponential distribution
X = stats.expon(1/lambda_param)
X.rvs(10)

array([0.68071508, 2.43763233, 0.50473311, 1.47122808, 1.75660599,
       0.76289065, 0.67613727, 1.60912259, 1.60607906, 1.3077734 ])

---

§5. Normal Distribution

A random variable $X \sim N(\mu, \sigma^2)$ follows a Normal distribution with parameter(s) $\mu, \sigma^2$.

* The support is
$$
\supp(X) = (-\infty, \infty)
$$
* The PDF is 
$$
\fx(x) = \frac{1}{\sqrt{2 \pi \sigma^2}} \exp \left( - \frac{(x - \mu)^2}{2 \sigma^2} \right)
$$
* The expected value is
$$
\begin{aligned}
\mathbb{E}(X) 
&= \int_{-\infty}^\infty x \cdot f_X(x) dx \\
&= \int_{-\infty}^\infty x \cdot \frac{1}{\sqrt{2 \pi \sigma^2}} \exp \left( - \frac{(x - \mu)^2}{2 \sigma^2} \right) dx \\
&= \mu
\end{aligned}
$$
* The variance is
$$
\begin{aligned}
\var(X) 
&= \E(X^2) - \E(X)^2 \\
&= (\mu^2 +\sigma^2) -  \mu^2 \\
&= \sigma^2
\end{aligned}
$$

We can generate $10$ random samples from a Normal distribution as follows:

In [15]:
# Define the mean and variance
mu = 0      
sigma = 1  

# Generate 10 random samples from a Normal distribution
X = stats.norm(mu, sigma)
X.rvs(10)

array([-0.48802655,  0.23372618,  0.72861175, -0.22868435,  0.65923766,
        1.61051246, -0.42020337,  0.98094643,  0.03758564, -2.55113964])

---

§6. Chi-squared Distribution

A random variable $X \sim \chi^2(k)$ follows a Chi-squared distribution with parameter(s) $k$.

* The support is
$$
\supp(X) = (0, \infty)
$$
* $X \sim \chi^2(k)$ is obtained using $k$ iid copies of a standard normal random variable $Z_1, Z_2, \dots, Z_k \sim N(0, 1)$ as follows:
$$
X = \sum_{i=1}^k Z_i^2 \quad \text{where} \quad Z_1, Z_2, \dots, Z_k \sim N(0,1)
$$
* The expected value is
$$
\mathbb E(X) = k
$$
* The variance is
$$
\var(X) = 2k
$$

We can generate $10$ random samples from a Chi-squared distribution as follows:

In [16]:
# Define the degrees of freedom
df = 4  

# Generate 10 random samples from a Chi-squared distribution
X = stats.chi2(df)
X.rvs(10)

array([0.71129535, 1.85052618, 1.80899675, 5.49762089, 1.888664  ,
       0.89478173, 8.01857061, 3.85134259, 0.58744002, 5.50658421])

---

§7. Student's t Distribution

A random variable $X \sim t(k)$ follows a Student's $t$ distribution with parameter(s) $k$. 

* The support is
$$
\supp(X) =  (-\infty, \infty)
$$

* Given $Z \sim N(0,1)$ and $Y \sim \chi^2(k)$ with $Z \perp Y$, a Student's $t$ random variable $X$ is obtained as follows:
$$
X = \frac{Z}{\sqrt{Y/k}}
$$


We can generate $10$ random samples from a Student's $t$ distribution as follows:

In [17]:
from scipy.stats import t

# Define the degrees of freedom
k = 10  

# Generate 10 random samples from a Student's t distribution
X = stats.t(k)
X.rvs(10)

array([-1.76664971, -0.47390123, -0.28314103, -0.36211341, -0.8748614 ,
       -0.18752773,  0.59074411,  0.40418931,  2.40940184, -1.72207336])

---

§8. $F$ Distribution

A random variable $X \sim F(k_1, k_2)$ follows an $F$ distribution with parameter(s) $k_1, k_2$.

* The support is
$$
\supp(X) = (0, \infty)
$$

* Given $Y \sim \chi^2(k_1)$ and $Z \sim \chi^2(k_2)$ with $Y \perp Z$, an $F$ random variable $X$ is obtained as follows:
$$
X = \frac{Y/k_1}{Z/k_2} 
$$

We can generate $10$ random samples from a Normal distribution as follows:

In [18]:
from scipy.stats import f

# Define the degrees of freedom for the numerator and the denominator
k1 = 5  
k2 = 10  

# Generate 10 random samples from an F distribution
X = stats.f(k1,k2)
X.rvs(10)

array([0.41841511, 0.32275048, 0.19555319, 1.48789167, 1.598553  ,
       1.04146675, 1.74992224, 0.15485536, 0.33640557, 0.41629034])

---

Suppose $X_1, X_2, \dots, X_n$ are $n$ iid samples from a distribution with mean $\E(X) = M$ and variance $\var(X) = V$.

Let $$\Xbar = \frac{1}{n} \sum_{i=1}^n X_i$$ be the sample mean and $$S^2 = \frac{1}{n-1} \sum_{i=1}^n (X_i - \Xbar)^2$$ be the sample variance.

**Law of large Numbers**

In english, the law of large numbers says that as the size of a sample drawn from a population increases, the sample mean will get closer to the population mean. 

$$
\frac{1}{n} \sum_{i=1}^n X_i \rightarrow \mathbb{E}(X) \quad \text{as } n \rightarrow \infty
$$


**Central Limit Theorem**

In english, the central limit theorem says that when you have a large sample (or many repeated samples) from a population, the distribution of the sample means will approach a normal distribution, regardless of the shape of the original distribution. 

$$
\frac{\overline{X} - \mathbb{E}(X)}{\sqrt{\text{Var}(X)}} \Longrightarrow N(0,1) \quad \text{as } n \rightarrow \infty
$$



---
---

## Thu, Apr 11th

#### Quantile
Given a random variable $X \sim D$ and a number $\alpha \in (0, 1)$, the $\alpha$-quantile of $X$ is the value $q_\alpha$ such that

$$
\pr(X \le q_\alpha) = \alpha
$$

In terms of the CDF, this is

$$
F_X(q_\alpha) = \alpha
$$

In other words, $q_\alpha$ is the value such that the probability that $X$ is less than or equal to $q_\alpha$ is exactly $\alpha$.

### Empirical CDF

Given samples $X_1, X_2, \dots, X_n$ from a random variable $X$, the empirical CDF is given by

$$
\hat{F}_n(x) = \frac{1}{n} \sum_{i=1}^n I(X_i \le x)
$$

where $I(X_i \le x)$ is the indicator function, i.e., 

$$
I(X_i \le x) = \begin{cases}
1 & \text{if } X_i \le x \\
0 & \text{if } X_i > x
\end{cases}
$$

Using the empricial CDF, $\hat F_n(x)$, we can compute the **empricial quantile** of $\Xn$, which is 

$$
\hat q_\alpha = (100 \times \alpha) \% \text{ of } \Xn
$$


#### Statistic

Suppose $\Xn$ is sampled iid from a distribution $D(\theta)$ where $\theta$ is the parameter.

Then, intuitively, a statistic $\hat\theta \equiv \hat\theta(\Xn)$ is **our best guess** for the parameter $\theta$.


#### Sampling Distribution

Since $\Xn$ are all random variables, the statistic $\hat\theta$ is also random.

In words, the sampling distribution of $\hat\theta$ is the distribution of $\hat\theta$ when $\Xn$ are drawn from $D(\theta)$.

#### Intuition behind Sampling Distributions

If we call the process of sampling $\Xn$ from $D(\theta)$ as a "**random experiment**", then let

* $\hat\theta^{(1)}, \hat\theta^{(1)}, \dots, \hat\theta^{(N)}$ be the statistics obtained from each of $N$ random experiments.

Then, the sampling distribution of $\hat\theta$ roughly is approximated by the distribution of the sample statistics  $\hat\theta^{(1)}, \hat\theta^{(1)}, \dots, \hat\theta^{(N)}$ obtained from each of $N$ random experiments.


---

#### Confidence Interval

The **$100 \times (1-\alpha)\%$ confidence interval** for a parameter $\theta$ is an interval $[\la, \ua]$ such that:

$$
\mathbb{P}(\la \leq \theta \leq \ua) = 1 - \alpha
$$

we denote this as $\ci(\theta) = [\la, \ua]$.

For a statistic $\hat\theta$ with standard error $\se(\hat\theta)$ the general formula for the $100 \times (1-\alpha)\%$ confidence interval is given by


$$
\ci(\theta, \alpha) = \Big[ \hat\theta - q_{1-\alpha/2} \times \se(\hat\theta),\;\;\; \hat\theta + q_{1-\alpha/2} \times \se(\hat\theta) \Big]
$$

#### Interpretation of Confidence Intervals

If we call the process of sampling $\Xn$ from $D(\theta)$ as a "**random experiment**" where $\theta^*$ is the true, unknown population parameter.  

Let

$$
[\la^{(1)}, \ua^{(1)}], [\la^{(2)}, \ua^{(2)}], \dots, [\la^{(N)}, \ua^{(N)}]
$$

be the $100 \times (1-\alpha)\%$ confidence intervals obtained from each of $N$ random experiments.




Then, the guarantee provided by the construction of the confidence interval is that if we were to repeat our random experiment N times and compute the CI of each experiment, approximately 
$100 \times (1-\alpha)\%$ of these CIs will contain the true population parameter $\theta^*$.

---

#### Examples of Confidence Intervals (from Math 183 or equivalent)

---

§1. One sample Proportion

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim \Ber(\theta)$ |
| Population parameter | $\theta$ = the proportion of success in the population |
| Statistic | $\hat\theta$ =  the number of successes divided by the sample size $n$ |
| Standard Error | $\se(\hat\theta) = \sqrt{\frac{\hat{\theta}(1-\hat{\theta})}{n}}$ |
| Sampling distribution | $D_{\hat\theta} = N\left(\hat{\theta}, \frac{\hat{\theta}(1-\hat{\theta})}{n}\right)$ |

The **99\% confidence interval** for $\theta$ is given by

$$
\begin{aligned}
CI(\theta, \alpha)
 &= \Bigg[\hat{\theta} - z_{0.005} \cdot \se, \ \  \hat{\theta} + z_{0.005} \cdot \se \Bigg]\\ \\
 &= \Bigg[\hat{\theta} - 2.576 \sqrt{\frac{\hat{\theta}(1-\hat{\theta})}{n}}, \ \  \hat{\theta} + 2.576 \sqrt{\frac{\hat{\theta}(1-\hat{\theta})}{n}}\Bigg]
\end{aligned}
$$

---

§2. Difference of two proportions

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim Ber(\theta_X)$  and $\Ym \sim Ber(\theta_Y)$|
| Population parameter | $\theta = \theta_X - \theta_Y$ |
| Statistic | $\hat\theta = \hat{\theta}_X - \hat{\theta}_Y$ |
| Standard Error | $\se(\hat\theta) = \sqrt{\frac{\hat{\theta}_X(1-\hat{\theta}_X)}{n} + \frac{\hat{\theta}_Y(1-\hat{\theta}_Y)}{m}}$ |
| Sampling distribution | $D_{\hat\theta} = N\left( \hat{\theta}, \frac{\hat{\theta}_X(1 - \hat{\theta}_X)}{n} + \frac{\hat{\theta}_Y(1 - \hat{\theta}_Y)}{m} \right)$ |

The **97\% confidence interval** for $\theta$ is given by

$$
\begin{aligned}
CI(\theta, \alpha)
 &= \Bigg[\hat{\theta} - z_{0.015} \cdot \se, \ \  \hat{\theta} + z_{0.015} \cdot \se \Bigg]\\ \\
  &= \Bigg[\hat{\theta} - 2.17 \cdot \se, \ \  \hat{\theta} + 2.17 \cdot \se \Bigg]\\ \\
 \end{aligned} 
$$

---

§3. One sample Mean (with unknown variance)

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim ...$ |
| Population parameter | $\theta = ...$ |
| Statistic | $\hat\theta = ...$ |
| Standard Error | $\se(\hat\theta) = ...$ |
| Sampling distribution | $D_{\hat\theta} = ...$ |

The **93\% confidence interval** for $\theta$ is given by

$$
\ci(\theta, \alpha) = ...
$$

---

§1. Difference of two means (with unknown variances)

| Description | Answer |
|:---|:---|
| Assumption | $\Xn \sim ...$ and $\Ym \sim ...$ |
| Population parameter | $\theta = ...$ |
| Statistic | $\hat\theta = ...$ |
| Standard Error | $\se(\hat\theta) = ...$ |
| Sampling distribution | $D_{\hat\theta} = ...$ |

The **96\% confidence interval** for $\theta$ is given by

$$
\ci(\theta, \alpha) = ...
$$

---