# Week 1 Summary
> NAME: $\color{red}{\text{    Yuan Ji     }}$
> 
> PID: $\color{red}{\text{    A16822092     }}$
>
> 
---

I certify that the following write-up is my own work, and have abided by the UCSD Academic Integrity Guidelines.

- [x] Yes
- [ ] No

% # %load tex-macros
<div hidden>
\newcommand{\require}[1]{}

$\require{begingroup}\require{newcommand}$
$\long\def \forcecommand #1{\providecommand{#1}{}\renewcommand{#1}}$
$\forcecommand{\defeq}{\stackrel{\small\bullet}{=}}$
$\forcecommand{\ra}{\rangle}$
$\forcecommand{\la}{\langle}$
$\forcecommand{\pr}{{\mathbb P}}$
$\forcecommand{\qr}{{\mathbb Q}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\av}{{\boldsymbol{a}}}$
$\forcecommand{\bv}{{\boldsymbol{b}}}$
$\forcecommand{\cv}{{\boldsymbol{c}}}$
$\forcecommand{\dv}{{\boldsymbol{d}}}$
$\forcecommand{\ev}{{\boldsymbol{e}}}$
$\forcecommand{\fv}{{\boldsymbol{f}}}$
$\forcecommand{\gv}{{\boldsymbol{g}}}$
$\forcecommand{\hv}{{\boldsymbol{h}}}$
$\forcecommand{\nv}{{\boldsymbol{n}}}$
$\forcecommand{\sv}{{\boldsymbol{s}}}$
$\forcecommand{\tv}{{\boldsymbol{t}}}$
$\forcecommand{\uv}{{\boldsymbol{u}}}$
$\forcecommand{\vv}{{\boldsymbol{v}}}$
$\forcecommand{\wv}{{\boldsymbol{w}}}$
$\forcecommand{\zerov}{{\mathbf{0}}}$
$\forcecommand{\onev}{{\mathbf{0}}}$
$\forcecommand{\phiv}{{\boldsymbol{\phi}}}$
$\forcecommand{\cc}{{\check{C}}}$
$\forcecommand{\xv}{{\boldsymbol{x}}}$
$\forcecommand{\Xv}{{\boldsymbol{X}\!}}$
$\forcecommand{\yv}{{\boldsymbol{y}}}$
$\forcecommand{\Yv}{{\boldsymbol{Y}}}$
$\forcecommand{\zv}{{\boldsymbol{z}}}$
$\forcecommand{\Zv}{{\boldsymbol{Z}}}$
$\forcecommand{\Iv}{{\boldsymbol{I}}}$
$\forcecommand{\Jv}{{\boldsymbol{J}}}$
$\forcecommand{\Cv}{{\boldsymbol{C}}}$
$\forcecommand{\Ev}{{\boldsymbol{E}}}$
$\forcecommand{\Fv}{{\boldsymbol{F}}}$
$\forcecommand{\Gv}{{\boldsymbol{G}}}$
$\forcecommand{\Hv}{{\boldsymbol{H}}}$
$\forcecommand{\alphav}{{\boldsymbol{\alpha}}}$
$\forcecommand{\epsilonv}{{\boldsymbol{\epsilon}}}$
$\forcecommand{\betav}{{\boldsymbol{\beta}}}$
$\forcecommand{\deltav}{{\boldsymbol{\delta}}}$
$\forcecommand{\gammav}{{\boldsymbol{\gamma}}}$
$\forcecommand{\etav}{{\boldsymbol{\eta}}}$
$\forcecommand{\piv}{{\boldsymbol{\pi}}}$
$\forcecommand{\thetav}{{\boldsymbol{\theta}}}$
$\forcecommand{\tauv}{{\boldsymbol{\tau}}}$
$\forcecommand{\muv}{{\boldsymbol{\mu}}}$
$%$
$\forcecommand{\sd}{\text{SD}}$
$\forcecommand{\se}{\text{SE}}$
$\forcecommand{\med}{\text{median}}$
$\forcecommand{\median}{\text{median}}$
$%$
$\forcecommand{\Ber}{{\text{Ber}}}$
$\forcecommand{\Bin}{{\text{Bin}}}$
$\forcecommand{\Geo}{{\text{Geo}}}$
$\forcecommand{\Unif}{{\text{Unif}}}$
$\forcecommand{\Poi}{{\text{Poi}}}$
$\forcecommand{\Exp}{{\text{Exp}}}$
$\forcecommand{\Chisq}{{\chi^2}}$
$\forcecommand{\N}{\mathbb{N}}$
$\forcecommand{\iid}{{\stackrel{iid}{\sim}}}$
$\forcecommand{\px}{p_{X}}$
$\forcecommand{\fx}{f_{X}}$
$\forcecommand{\Fx}{F_{X}}$
$\forcecommand{\py}{p_{Y}}$
$\forcecommand{\pxy}{p_{X,Y}}$
$\forcecommand{\po}{{p_0}}$
$\forcecommand{\pa}{{p_a}}$
$\forcecommand{\Xbar}{\overline{X}}$
$\forcecommand{\Ybar}{\overline{Y}}$
$\forcecommand{\Zbar}{\overline{Z}}$
$\forcecommand{\nXbar}{n \cdot \overline{X}}$
$\forcecommand{\nYbar}{n \cdot \overline{Y}}$
$\forcecommand{\nZbar}{n \cdot \overline{Z}}$
$\forcecommand{\Xn}{X_1, X_2, \dots, X_n}$
$\forcecommand{\Xm}{{X_1, X_2, \dots, X_m}}$
$\forcecommand{\Yn}{Y_1, Y_2, \dots, Y_n}$
$\forcecommand{\Ym}{{Y_1, Y_2, \dots, Y_m}}$
$\forcecommand{\sumXn}{X_1 + X_2 + \dots + X_n}$
$\forcecommand{\sumym}{Y_1 + Y_2 + \dots + Y_m}$
$\forcecommand{\la}{\ell_\alpha}$
$\forcecommand{\ua}{u_\alpha}$
$\forcecommand{\at}{{\alpha/2}}$
$\forcecommand{\mux}{\mu_{X}}$
$\forcecommand{\muy}{\mu_{Y}}$
$\forcecommand{\sx}{\sigma_{X}}$
$\forcecommand{\sy}{\sigma_{Y}}$
$\forcecommand{\pvalue}{$p$-value}$
$\forcecommand{\Ho}{H_{0}}$
$\forcecommand{\Ha}{H_{a}}$

\vskip-\parskip
\vskip-\baselineskip
</div>

---

## Key Takeaways from Week 1


#### Tuesday: 
**Statistical Thinking** from the boiling-tea story of Fisher:

* Experiment Design
* P value
* A/B Testing: evaluate the effectiveness of  new features, algorithms, etc.
* Genome-wide association studies (GWAS): inherently a hypothesis testing problem in ultra-high-dimensional setting.
* Astrophysics and cosmology: apply classical statistical principles

**Data Analysis**
We use the data to identify patterns. 
The data we analyze is assumed to be fixed.

**Statistical Inference**
We use the data to understand the population from which the data was collected.
The data is assumed to be one instance from a universe of datasets we could have collected.

**Frictionless Replications**
The currency of discourse today. Researchers are thinking: Can't I just try this now?

**Syllabus Overview & Class Expectation**


#### Thursday

Some basics of **Markdown and LATEX**

---

## Tue, Apr 2nd

### Basics of markdown

**Bullet Lists and Numbered Lists**

**1.1: Creating sections**

# Level 1
---
## Level 2
### Level 3
#### Level 4

**1.2: Bullet lists and numbered lists**

Bullet list:
* Item 1
    - Subitem 1
        - Subsubitem 1
* Item 2
* Item 3

Enumeration List:
1. Item 1
    * Subitem 1
        * Subsubitem 1
2. Item 2
3. Item 3

**1.3: Math**

$\LaTeX$

In-line math expression $x^2_1 + \beta = 2$, and $x^2_1 + \omega = 2$.

Own-line math expression $$ x^2_1 + \beta = 2$$.

Multiple equations
$$
\overline{x} = \frac{1}{n}\sum_{i=1}^n X_i\\
\text{Var}(X) = \frac{1}{n-1} \sum_{i=1}^n (X_i -
\overline{X}^2)\\
$$

Using aligned
$$
\begin{aligned}
\overline{x} &= \frac{1}{n}\sum_{i=1}^n X_i\\
\text{Var}(X) 
&= \mathbb{E} (X - \mathbb{E}(X))^2\\
&= \frac{1}{n-1} \sum_{i=1}^n (X_i -
\overline{X}^2)\\
\end{aligned}
$$




**Boxed & Colored Equations**

$$
\boxed{
    \color{magenta}{
        \frac{1}{n}\sum_{i=1}^n X_i = \overline{X}
    }
}
$$

This is inline math $
% \boxed{
    \color{blue}{
        \frac{1}{n}\sum_{i=1}^n X_i = \overline{X}
    }
% }
$ and the sentence continues here.

**Math Macros**

$$
\renewcommand{\newsum}[2]{\sum_{i=#1}^{#2}}
\newsum{0}{m} a_i = \sum_{i=0}^m a_i
$$

$$
\renewcommand{\Xn}{X_1, X_2, \cdots, X_n}
\newcommand{\Ho}{H_0}
\Xn \text{ is sampled iid from a distribution } \Ho
$$

**2.1: Int, Float, Booleans, Strings**

In [3]:
type(19)

int

In [4]:
type(19.0)

float

In [5]:
True, False

(True, False)

In [6]:
"abs"+"123"

'abs123'

**Arithmetric operations (+,-,/,%,//,*)**

In [9]:
13/4

3.25

In [11]:
# remainder
13%4 

1

In [12]:
# quotient
13//4

3

In [10]:
13**4

28561

---

**2.2: Arrays, Tuples, Dicts**

In [16]:
import math

In [13]:
# array
[1,2,3] + [4,5,6]

[1, 2, 3, 4, 5, 6]

In [14]:
# tuple
(1,2,3)

(1, 2, 3)

In [18]:
# dict
{"a":1,"b":2,"c": math.pi}.keys()

dict_keys(['a', 'b', 'c'])

In [19]:
for k,v in {"a":1,"b":2,"c": math.pi}.items():
    print(f'k={k},v={v}')

k=a,v=1
k=b,v=2
k=c,v=3.141592653589793


In [21]:
# sets
a={1,2,3,4,5}
b={5,6,7}
a.issubset(b)

False

In [22]:
a.union(b)

{1, 2, 3, 4, 5, 6, 7}

In [23]:
a.difference(b)

{1, 2, 3, 4}

In [24]:
a.symmetric_difference(b)

{1, 2, 3, 4, 6, 7}

**2.3 Control Flow**

In [25]:
# for
for i in range(1,10):
    if i%2 == 0:
        print(f"{i} is a multiple of 4")
    elif i % 2 == 0:
        print(f"{i} is even")
    else:
        print(f"{i} is odd")

1 is odd
2 is a multiple of 4
3 is odd
4 is a multiple of 4
5 is odd
6 is a multiple of 4
7 is odd
8 is a multiple of 4
9 is odd


In [27]:
# while
n = 0
while n < 10:
    print(n)
    n = n+1

0
1
2
3
4
5
6
7
8
9


**2.4 Functions**

In [30]:
def fibonacci(n):
    return 0 if n==0 else 1 if n==1 else fibonacci(n-1) + fibonacci(n-2)

In [31]:
fibonacci(7)

13

**2.4.1 Anonymous functions**

In [32]:
fib = lambda n: 0 if n==0 else 1 if n==1 else fib(n-1) + fib(n-2)

---

## Thu, Apr 4th

**Vectors**

A vector $v \in \R^n$ represents a point 

$$
v = (v_1, v_2, \ldots, v_n)^T
$$

in $n$-dimensional space where each $v_i$ is a number.

When you add two vectors:
$$
v = (v_1, v_2, \ldots, v_n)^T
$$
$$
w = (w_1, w_2, \ldots, w_n)^T
$$
$$
v+w = (v_1+w_1, v_2+w_2, \ldots, v_n+w_n)^T
$$

In [33]:
import numpy as np

In [34]:
v = np.array([1,2,3])
w = np.array([1,2,3])
v+w

array([2, 4, 6])

When you multiply a vector by a scalar:

In [37]:
2*v

array([2, 4, 6])

You can "multiply" two vectors in two different ways:

1. dot product
2. cross product


**dot product**

The dot product of two vectors $u, v \in \R^n$ is the sum of the element-wise product

$$
u \cdot v = \sum_{i=1}^n u_i v_i
$$

The geometric interpretation of the dot product is given by:

$$
u \cdot v = \| u \| \| v \| \cos\Big(\angle(u, v)\Big)
$$

**cross product**

The cross product of two vectors $u, v \in \R^n$ the vector $w$ which is perpendicular to the linear space _spanned_ by $u$ and $v$, i.e.
$$
w \perp \text{span}\{u, v\}
$$
and whose magnitude is 
$$
\|w\| = \|u\| \|v\| \sin\big(\angle\theta(u, v)\big)
$$

In [36]:
# dot product of v^T*w
v*w

array([1, 4, 9])

**Matrices**

Intuitively, a matrix is a transformation.

The transformation of a vector $v \in \R^n$ by a matrix $A \in \R^{m \times n}$ is another vector $w= f_A(v) = Av \in \R^m$ whose components are given by

\begin{align*}
    w_{1} &= \sum_{j=1}^n A_{1j}v_{j} \\
    w_{2} &= \sum_{j=1}^n A_{2j}v_{j} \\
    &\vdots \\
    w_{m} &= \sum_{j=1}^n A_{mj}v_{j}
\end{align*}

3-dimensional matrix is a tensor, so as any higher dimensional matrices.

When a matrix acts on a vector, you get ...

In [38]:
import numpy as np

# Creating vectors and matrices
vector = np.array([2,3])
matrix = np.array([
        [1.0, -1.0],
        [-1.0, 1.0],
    ])

# Calculating the product
product = matrix @ vector
product

array([-1.,  1.])

**Basic linear algebra operations:**
1. Norm: The norm of a vector is a measure of the vector's length or magnitude.
2. Dot product: The dot product of two vectors $u, v \in \R^n$ is the sum of the element-wise product

$$
u \cdot v = \sum_{i=1}^n u_i v_i
$$
4. Matrix transpose: The transpose of a matrix is an operation that flips a matrix over its diagonal, switching the matrix's row and column indices.
5. Matrix inverse: The inverse of a square matrix A is a matrix such that when it is multiplied by A, it results in the identity matrix. The matrix A must be non-singular (having a non-zero determinant) for the inverse to exist.


**Slightly more advanced linear algebra operations**

If we're given a system of equations, for example, 

$$
\begin{align*}
2x + 3y &= 5 \\
4x + 5y &= 6
\end{align*}
$$

We can represent it in the matrix-vector form as 
$$
\begin{bmatrix}
2 & 3 \\
4 & 5\\
\end{bmatrix} 
\begin{bmatrix}
x \\
y \\
\end{bmatrix}  = \begin{bmatrix}
5 \\
6 \\
\end{bmatrix}
$$

The solution for the unknown variables, $(x, y)$ is given by 
$$
\begin{bmatrix}
-3.5 \\
4 \\
\end{bmatrix} 
$$

In code, we can do this as follows: 

In [39]:
# Solving a system of linear equations
A = np.array([[2, 3], [4, 5]])
b = np.array([5, 6])
solution = np.linalg.solve(A, b)

solution

array([-3.5,  4. ])

---

**Eigenvalues and eigenvectors**

Given an $n \times n$ matrix $A$, the eigenvalue of $A$ is the scalar $\lambda$ such that 
$$
A\mathbf{v} = \lambda \mathbf{v}
$$

The eigenvector of $A$ is the vector $v$ such that for a given eigenvalue 
$\lambda$ the equation $A\mathbf{v} = \lambda \mathbf{v}$ holds true. 

Intuitively, the eigenvector of a matrix describes the direction that is not changed by the matrix transformation.

In code, we can compute the eigenvalues and eigenvectors of a matrix as follows:

In [41]:
A = np.array([[2, 1], [1, 2]])

eigenvalues, eigenvectors = np.linalg.eig(A)

We can verify that the eigenvalues and eigenvectors are correct by running the following code and ensuring that the output matches the expected values:


In [42]:
largest_index = np.argmax(eigenvalues)
lambda1 = eigenvalues[largest_index]  # Largest eigenvalue
v1 = eigenvectors[:, largest_index] # Corresponding eigenvector

# Expected value of Av
expected_value = lambda1 * v1

# Actual value of Av
Av = A @ v1

# Check if the expected value and actual value are equal
np.allclose(expected_value, Av)

True